import {
  AlertTriangle,
  ArrowRight,
  Building2,
  CheckCircle2,
  CircleDashed,
  DoorOpen,
  ExternalLink,
  FileSearch,
  Gauge,
  Layers,
  Loader2,
  Mail,
  MapPin,
  MessageSquareQuote,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  PenLine,
  Radar,
  ShieldCheck,
  Sun,
  Target,
  TrendingUp,
  Users,
  XCircle,
} from "lucide-react";

export const icons = {
  action: ArrowRight,
  blocked: XCircle,
  error: AlertTriangle,
  externalLink: ExternalLink,
  fit: Gauge,
  firm: Building2,
  loading: Loader2,
  location: MapPin,
  mail: Mail,
  moon: Moon,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  pending: CircleDashed,
  people: Users,
  play: Target,
  quote: MessageSquareQuote,
  room: DoorOpen,
  rooms: Layers,
  research: FileSearch,
  scan: Radar,
  signal: TrendingUp,
  success: CheckCircle2,
  sun: Sun,
  trust: ShieldCheck,
  write: PenLine,
} as const;

export type IconName = keyof typeof icons;
